# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - dev
      - main

steps:
- script: |
    echo I am main CI pipeline, Use me to trigger CD pipeline.
  displayName: 'Run a Demo CI - trigger'
