# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

on:
  push:
    branches:
    - main
    - release/*

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
    - name: Display the path
      shell: bash
      run: echo ""

